apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevirt-redfish.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kubevirt-redfish.labels" . | nindent 4 }}
    {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "kubevirt-redfish.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubevirt-redfish.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ include "kubevirt-redfish.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- with .Values.deployment.container.ports }}
        ports:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.container.env }}
        env:
          {{- if kindIs "map" . }}
          {{- range $key, $value := . }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- else if kindIs "slice" . }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
        {{- with .Values.deployment.container.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.container.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.container.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.container.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- if .config }}
        - name: {{ .config.name }}
          {{- toYaml .config | nindent 10 }}
        {{- end }}
        {{- if .temp }}
        - name: {{ .temp.name }}
          {{- toYaml .temp | nindent 10 }}
        {{- end }}
      {{- end }} 