{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kubevirt-redfish.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kubevirt-redfish.labels" . | nindent 4 }}
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "kubevirt-redfish.fullname" . }}
    weight: 100
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 