{{- if .Values.rbac.scc.custom }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ .Values.rbac.scc.customName }}
  labels:
    {{- include "kubevirt-redfish.labels" . | nindent 4 }}
    {{- with .Values.rbac.scc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.scc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
  - min: {{ .Values.rbac.scc.fsGroup.min }}
    max: {{ .Values.rbac.scc.fsGroup.max }}
priority: {{ .Values.rbac.scc.priority }}
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: MustRunAsRange
  uidRangeMin: {{ .Values.rbac.scc.runAsUser.min }}
  uidRangeMax: {{ .Values.rbac.scc.runAsUser.max }}
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    level: "s0"
    role: "r"
    type: "container_t"
    user: "u"
seccompProfiles:
- DockerDefault
supplementalGroups:
  type: MustRunAs
  ranges:
  - min: {{ .Values.rbac.scc.supplementalGroups.min }}
    max: {{ .Values.rbac.scc.supplementalGroups.max }}
users:
- system:serviceaccount:{{ .Values.global.namespace }}:{{ include "kubevirt-redfish.serviceAccountName" . }}
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
{{- end }} 